# Generated by Django 3.1.7 on 2022-06-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(default='My wallet', max_length=256, verbose_name='wallet name')),
                ('slug', models.SlugField(default='wallet-slug', editable=False, max_length=255, verbose_name='address of the wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
