# Generated by Django 3.1.7 on 2021-03-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=256, verbose_name='the reason of the income')),
                ('price', models.FloatField(default=0.0, max_length=256, verbose_name='the value of income money')),
            ],
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=256, verbose_name='the reason of the spent')),
                ('price', models.FloatField(default=0.0, max_length=256, verbose_name='the value of spent money')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('abstractmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallet.abstractmodel')),
                ('name', models.CharField(default='', max_length=256, verbose_name='wallet name')),
                ('income', models.IntegerField(default=0, verbose_name='all of your incomes')),
                ('spent', models.IntegerField(default=0, verbose_name='all of your spents')),
                ('total_money', models.IntegerField(default=0, verbose_name='sum of spents and incomes')),
                ('slug', models.SlugField(default='wallet-slug', editable=False, max_length=255, verbose_name='address of the wallet')),
            ],
            bases=('wallet.abstractmodel',),
        ),
    ]
