# Generated by Django 3.1.7 on 2021-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='income',
            field=models.FloatField(default=0, verbose_name='all of your incomes'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='spent',
            field=models.FloatField(default=0, verbose_name='all of your spents'),
        ),
    ]
