# Generated by Django 3.1.7 on 2021-03-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210308_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='total_money',
            field=models.FloatField(default=0, verbose_name='sum of spents and incomes'),
        ),
    ]
