# Generated by Django 3.1.7 on 2022-06-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_auto_20220602_0651"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="No Name", max_length=256)),
                (
                    "description",
                    models.CharField(default="no description", max_length=256),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "price",
                    models.FloatField(
                        default=0.0,
                        max_length=256,
                        verbose_name="the value of Invest money",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallet.wallet"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
